# Generated by Django 4.1 on 2022-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("code", models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
