# Generated by Django 4.1 on 2022-08-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcomApp", "0002_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
