# Generated by Django 4.1 on 2022-08-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcomApp", "0003_alter_contactmessage_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordernumber", models.IntegerField()),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default=False,
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
